<?php
/**
 * @file
 * Install, update and uninstall functions for the commerce_userpoints_discount module.
 */

/**
 * Implement hook_uninstall().
 */
function commerce_userpoints_discount_uninstall() {
  variable_del('commerce_userpoints_discount_default_termid');
  variable_del('commerce_userpoints_discount_total_price_components');
  variable_del('commerce_userpoints_discount_royalties_multiple');
}

/**
 * Enable the new commerce_userpoints base module.
 */
function commerce_userpoints_discount_update_7001() {
  if (module_exists('commerce_userpoints_discount')) {
    module_enable(array('commerce_userpoints'));
  }
  menu_rebuild();
}
